[package]
name = "geomutil"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
util = { workspace = true }

[workspace]
members = [
  "util"
]

[workspace.dependencies]
util = { path = "./util" }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
